Review order page
devcareer/Dae-Alright-Frontend pull request #38
Opened 2020-01-07 21:42 UTC by bamiogunfemi

2020-01-10 16:08 UTC, Mlg29 requested changes
Hi, nice one.
little adjustment still need to be carried out.
you need to add padding to the proceed to payment button right above the order.

Also, the text should be All total and not your total.

Lastly, I went through your codes and i notice that for your review your order, payment and done part at the top of the page, u make use of a div, I'm thinking it should be navigation so as soon as the order is complete, it automatically move to the next link. I'm not sure if that can be done with a div

2020-01-11 07:26 UTC, Joggz requested changes
nices layout, thou it has to be centered, you should check the figma design again. Good job

2020-01-13 03:27 UTC, John-pels approved these changes

2020-01-14 00:10 UTC, bamiogunfemi commented
> Hi, nice one.
> little adjustment still need to be carried out.
> you need to add padding to the proceed to payment button right above the order.
> 
> Also, the text should be All total and not your total.
> 
> Lastly, I went through your codes and i notice that for your review your order, payment and done part at the top of the page, u make use of a div, I'm thinking it should be navigation so as soon as the order is complete, it automatically move to the next link. I'm not sure if that can be done with a div

Done

2020-01-14 08:28 UTC, merged